# SwiftLint Configuration for DirectorStudio

# Paths to include/exclude
included:
  - Sources
  - Tests

excluded:
  - .build
  - .git
  - automation

# Rules to enable/disable
disabled_rules:
  - trailing_whitespace
  - line_length

opt_in_rules:
  - empty_count
  - empty_string
  - force_unwrapping
  - implicitly_unwrapped_optional
  - overridden_super_call
  - prohibited_interface_builder
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - switch_case_on_newline
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - yoda_condition

# Custom rules
custom_rules:
  no_hardcoded_strings:
    name: "No Hardcoded Strings"
    regex: '"[A-Za-z0-9\s]+"'
    message: "Avoid hardcoded strings, use localized strings instead"
    severity: warning

# File length
file_length:
  warning: 500
  error: 1000

# Function length
function_body_length:
  warning: 50
  error: 100

# Line length
line_length:
  warning: 120
  error: 200
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true

# Type body length
type_body_length:
  warning: 300
  error: 500

# Identifier name
identifier_name:
  min_length: 1
  max_length: 60
  excluded:
    - id
    - url
    - urlRequest
    - globalValueKey

# Type name
type_name:
  min_length: 3
  max_length: 40

# Variable name
variable_name:
  min_length: 1
  max_length: 60
  excluded:
    - id
    - url
    - urlRequest
    - globalValueKey